version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloakdb
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=nikiakbar@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=nikiakbar@gmail.com
    ports:
      - 5555:80
    networks:
      - backend

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    depends_on:
      - postgres
    environment:
      #- KEYCLOAK_FRONTEND_URL=https://whatever.com
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=postgres
      - DB_VENDOR=POSTGRES
      - DB_DATABASE=keycloakdb
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
      - 8080:8080

    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
